### ISSUE TITLE
Failing on tutorial

### ISSUE THREAD

**Issue by FreekVanDooren** [GoogleCloudPlatform/appengine-guestbook-go#15]
Hi there,

I'm trying to follow this tutorial: https://cloud.google.com/appengine/docs/standard/go/getting-started/creating-guestbook.
However, I'm failing hard... With the following error:
```
INFO     2017-11-14 08:52:10,266 devappserver2.py:105] Skipping SDK update check.
INFO     2017-11-14 08:52:10,619 api_server.py:300] Starting API server at: http://localhost:61603
INFO     2017-11-14 08:52:11,201 dispatcher.py:251] Starting module "default" running at: http://localhost:8080
INFO     2017-11-14 08:52:11,209 admin_server.py:116] Starting admin server at: http://localhost:8000
ERROR    2017-11-14 08:52:12,327 instance_factory.py:194] Failed to build Go application: (Executed command: /usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8/bin/go-app-builder -app_base /Users/freekvandooren/GoglandProjects/appengine-guestbook-go -api_version go1 -arch 6 -dynamic -goroot /usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8 -gopath /usr/local/google-cloud-sdk/platform/google_appengine/gopath -nobuild_files ^^$ -incremental_rebuild -unsafe -binary_name _go_app -extra_imports appengine_internal/init -work_dir /var/folders/hd/w6gynpy55nbcr4x_wk13sn6c0000gn/T/tmpau3igRappengine-go-bin -gcflags -I,/usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8/pkg/darwin_amd64_appengine -ldflags -L,/usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8/pkg/darwin_amd64_appengine hello.go)
/var/folders/hd/w6gynpy55nbcr4x_wk13sn6c0000gn/T/tmpau3igRappengine-go-bin/hello.go:8: can't find import: "golang.org/x/net/context"

2017/11/14 09:52:12 Can't find package "golang.org/x/net/context" in $GOPATH: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/golang.org/x/net/context (from $GOROOT)
	/usr/local/google-cloud-sdk/platform/google_appengine/gopath/src/golang.org/x/net/context (from $GOPATH)
2017/11/14 09:52:12 Can't find package "google.golang.org/appengine" in $GOPATH: cannot find package "google.golang.org/appengine" in any of:
	/usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/google.golang.org/appengine (from $GOROOT)
	/usr/local/google-cloud-sdk/platform/google_appengine/gopath/src/google.golang.org/appengine (from $GOPATH)
2017/11/14 09:52:12 Can't find package "google.golang.org/appengine/datastore" in $GOPATH: cannot find package "google.golang.org/appengine/datastore" in any of:
	/usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/google.golang.org/appengine/datastore (from $GOROOT)
	/usr/local/google-cloud-sdk/platform/google_appengine/gopath/src/google.golang.org/appengine/datastore (from $GOPATH)
2017/11/14 09:52:12 Can't find package "google.golang.org/appengine/user" in $GOPATH: cannot find package "google.golang.org/appengine/user" in any of:
	/usr/local/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/google.golang.org/appengine/user (from $GOROOT)
	/usr/local/google-cloud-sdk/platform/google_appengine/gopath/src/google.golang.org/appengine/user (from $GOPATH)
2017/11/14 09:52:12 go-app-builder: build timing: 0×skip (0s total), 1×compile (61ms total), 0×link (0s total)
2017/11/14 09:52:12 go-app-builder: failed running compile: exit status 2
``` 
I'm also new to the Go language, so that is not particularly helpful, but I am thinking this tutorial probably did work when the cloud sdk was still using Go 1.6.

I have experimented with cloning from their respective repositories the imports on which the program is failing, which did seem to fix the immediate import problem, but then I ran into other issues, so I felt out of my depth.

Is there a way to switch the cloud sdk to Go 1.6? Alternatively, was I on the right track cloning those repositories, but somehow missing another step? 

Thank you in advance for any help you can offer.

Regards,

Freek

PS.
I feel I should mention I also installed Go 1.9 on a different track trying to learn Go.

**Comment by FreekVanDooren** [comment]
I don't know if anyone has seen this or planning to respond, but just in case anyone runs into the same problem here's what I did:
```
cd $GCLOUD_SDK/platform/google_appengine/goroot-1.8/src
git clone git@github.com:golang/appengine.git google.golang.org/appengine
git clone git@github.com:golang/protobuf.git github.com/golang/protobuf
git clone git@github.com:golang/net.git golang.org/x/net
cd golang.org/x/net
git checkout release-branch.go1.8
```
Where `$GCLOUD_SDK´ is wherever the google cloud sdk is installed.

**Comment by martinbonnin** [comment]
I have the exact same problem. Could you potentially reopen the issue ? I would love to hear from the maintainers about a more straightforward solution to that.

**Comment by FreekVanDooren** [comment]
Not a problem!

**Comment by zombiezen** [comment]
@broady Sounds like we might need to add instructions on how to run `go get`.

**Comment by yegle** [comment]
This issue has been reported for a month, why isn't it fixed yet?

**Comment by zombiezen** [comment]
A [previous comment](https://github.com/GoogleCloudPlatform/appengine-guestbook-go/issues/15#issuecomment-345456566) identified the workaround instructions.  I'm going to update the documentation with those instructions.

**Comment by yegle** [comment]
Would it be possible to just include the 3 packages in the SDK? I tried yesterday with the workaround but still get some errors (potentially because the head version in github has some backward compatibility issue).

If you can confirm a newly installed Google Cloud SDK + workaround works with the example project then that's great. Otherwise I can file another bug later today with reprod.

**Comment by zombiezen** [comment]
If we were to bundle it in the SDK, it would fall out of date and would be hard for users update.  Non-standard-library packages need to be pulled into your GOPATH.  I say "workaround" here because it's cloning into the SDK root instead of your GOPATH.  We will update the documentation shortly with the recommended instructions.

**Comment by yegle** [comment]
Well another solution is to have proper vendor support. I also tried vendoring the 3 libs in a vendor directory and got errors like https://groups.google.com/forum/#!topic/google-appengine-go/Xooyiq3kFTI

(and it drives me nuts when I can make the code work with `goapp`/`dev_appserver.py` but fail when `gcloud app deploy`)

**Comment by yegle** [comment]
FYI this is the error I got using the workaround mentioned in https://github.com/GoogleCloudPlatform/appengine-guestbook-go/issues/15#issuecomment-345456566

the runtime process gave a bad HTTP response: ''

```
2017/12/14 19:55:51 http: panic serving 127.0.0.1:59299: not an App Engine context
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc04219e0a0)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/net/http/server.go:1721 +0xd7
panic(0x7ba980, 0xc04200d4b0)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/runtime/panic.go:489 +0x2dd
google.golang.org/appengine/internal.Logf(0x4514028, 0xc042110540, 0x0, 0x8518f2, 0x25, 0xc04210a460, 0x1, 0x1)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/google.golang.org/appengine/internal/api_common.go:87 +0x10d
google.golang.org/appengine/log.Debugf(0x4514028, 0xc042110540, 0x8518f2, 0x25, 0xc04210a460, 0x1, 0x1)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/google.golang.org/appengine/log/api.go:19 +0x7a
main70084.handler(0xa1c380, 0xc0421602a0, 0xc04215aa00)
	main.go:39 +0xfb9
net/http.HandlerFunc.ServeHTTP(0x85ab98, 0xa1c380, 0xc0421602a0, 0xc04215aa00)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/net/http/server.go:1942 +0x4b
net/http.(*ServeMux).ServeHTTP(0xa4a340, 0xa1c380, 0xc0421602a0, 0xc04215aa00)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/net/http/server.go:2238 +0x137
appengine_internal.handleFilteredHTTP(0xa1c380, 0xc0421602a0, 0xc04215a800)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/appengine_internal/api_dev.go:102 +0x2b4
net/http.HandlerFunc.ServeHTTP(0x859e90, 0xa1c380, 0xc0421602a0, 0xc04215a800)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/net/http/server.go:1942 +0x4b
net/http.serverHandler.ServeHTTP(0xc0420d49a0, 0xa1c380, 0xc0421602a0, 0xc04215a800)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc04219e0a0, 0xa1ca00, 0xc04210c3c0)
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
	C:/Users/yegle/AppData/Local/Google/Cloud SDK/google-cloud-sdk/platform/google_appengine/goroot-1.8/src/net/http/server.go:2668 +0x2d5
```

**Comment by yegle** [comment]
Sorry wrong log in the previous comment (it demonstrate a different issue of the workaround).

With the workaround, part4 of appengine-guestbook-go gave the following compiling error:

```
$ dev_appserver.py .
INFO     2017-12-14 20:44:13,549 devappserver2.py:105] Skipping SDK update check.
INFO     2017-12-14 20:44:13,589 api_server.py:308] Starting API server at: http://localhost:60339
INFO     2017-12-14 20:44:13,592 dispatcher.py:255] Starting module "default" running at: http://localhost:8080
INFO     2017-12-14 20:44:13,594 admin_server.py:146] Starting admin server at: http://localhost:8000
ERROR    2017-12-14 20:44:16,549 instance_factory.py:196] Failed to build Go application: (Executed command: C:\Users\yegle\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\goroot-1.8\bin\go-app-builder.exe -app_base C:\Users\yegle\git\appengine-guestbook-go -api_version go1 -arch 6 -dynamic -goroot C:\Users\yegle\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\goroot-1.8 -gopath C:\Users\yegle\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\gopath -nobuild_files ^^$ -incremental_rebuild -unsafe -binary_name _go_app -extra_imports appengine_internal/init -work_dir z:\temp\tmplsjmajappengine-go-bin -gcflags -I,C:\\Users\\yegle\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\platform\\google_appengine\\goroot-1.8\\pkg\\windows_amd64_appengine -ldflags -L,C:\\Users\\yegle\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\platform\\google_appengine\\goroot-1.8\\pkg\\windows_amd64_appengine hello.go)
C:\Users\yegle\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\goroot-1.8\src\google.golang.org\appengine\user\user_classic.go:18: undefined: internal.ClassicContextFromContext
C:\Users\yegle\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\goroot-1.8\src\google.golang.org\appengine\user\user_classic.go:38: undefined: internal.ClassicContextFromContext
```

**Comment by martinbonnin** [comment]
As a newcomer to golang (not to the appengine), I feel uncomfortable manually cloning/checking out github repos directly into the google cloud SDK location. Wouldn't it be better to have a separate GOPATH ? Also, a solution using go get (or goapp get) would seem more natural.

Also, being able to install all the dependencies in one step instead of a bunch of commands would be greatly appreciated (node has `npm i`, gradle installs dependencies automatically).

**Comment by ctalladen78** [comment]
wtf this should not be an issue google. i put all the blame on the dev team. how is it that a hello world doesnt even compile for people? it should be straightforward and intuitive so no need for hacks and workaround. you people really dont give a shit

**Comment by tswast** [comment]
Sorry for the trouble you all have been having with this tutorial. I am investigating why the tutorial is using a sample which has not been updated in 4 years and will work to get the tutorial updated.

In the meantime, I recommend you check out the samples at https://github.com/GoogleCloudPlatform/golang-samples/tree/master/appengine/helloworld as a more maintained set of samples.

**Comment by enocom** [comment]
This project has been replaced with [this one](https://github.com/GoogleCloudPlatform/golang-samples/tree/master/appengine/gophers), whose corresponding docs may be found [here](https://cloud.google.com/appengine/docs/standard/go/building-app/).

@FreekVanDooren If you see similar troubles with the new getting started tutorial, please open an issue with any problems you encounter on [this repo](https://github.com/GoogleCloudPlatform/golang-samples).
